version: '3.7'

services:

  hydra_storage:
    image: mysql:8.0
    volumes:
       - ./hydra_storage:/var/lib/mysql
    deploy:
      endpoint_mode: "dnsrr"
    env_file:
      - ./config/mysql.env
    networks:
      - lockdown
    user: "1000"
    expose:
      - 3306
    restart: on-failure

  idp_storage:
    image: postgres:12
    volumes:
      - ./idp_storage:/var/lib/postgresql/data
    deploy:
      endpoint_mode: "dnsrr"
    env_file:
      - ./config/postgres.env
    networks:
      - lockdown
    #user: "1000:1000"
    expose:
      - 5432
    restart: on-failure

  aap_storage:
    image: neo4j:3.5.0
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - ./aap_storage:/data
    env_file:
      - ./config/neo4j.env
    networks:
      - lockdown
      - public
    expose:
      - 7474
      - 7687
    ports:
      - "7474:7474"
      - "7687:7687"
    user: "1000"
    restart: on-failure

networks:
  lockdown: # No external network allowed for storage services
    name: opensentry_lockdown
    internal: true
  public: # required to be able to use localhost:7474 for neo4j debugging
    name: public
