version: '3.7'

services:

  mysqld:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
       - ./mysqldata:/var/lib/mysql
    deploy:
      endpoint_mode: "dnsrr"
    env_file:
      - ./config/use/mysql.env
    networks:
      - lockdown
    user: "1000"
    expose:
      - 3306
    restart: on-failure

  neo4j:
    image: neo4j/neo4j-arm64-experimental:4.3.1-arm64
    # platform: linux/amd64
    volumes:
      - ./neo4jdata:/data
      - ./config/use/neo4j.conf:/conf/neo4j.conf:Z

        # certificate
      - ./certs/neo4j.crt:/var/lib/neo4j/certificates/bolt/public.crt
      - ./certs/neo4j.key:/var/lib/neo4j/certificates/bolt/private.key

      - ./certs/neo4j.crt:/var/lib/neo4j/certificates/https/public.crt
      - ./certs/neo4j.key:/var/lib/neo4j/certificates/https/private.key
    env_file:
      - ./config/use/neo4j.env
    networks:
      - lockdown
      - public
    expose:
      - 7474
      - 7687
    ports:
      - "7474:7474"
      - "7687:7687"
    user: "1000"
    restart: on-failure

networks:
  lockdown: # No external network allowed for storage services
    name: opensentry_lockdown
    internal: true
  public: # required to be able to use localhost:7474 for neo4j debugging
    name: public
