version: '3.7'

services:

  aap-migrate:
    build:
      context: ../../aap
      dockerfile: Dockerfile
    entrypoint: ""
    command:
      ./aap --migrate
    networks:
      - lockdown
    environment:
      - CONFIG_DISCOVERY_PATH=/discovery.yml
      - CONFIG_APP_PATH=/app.yml
    volumes:
      - ../../aap/model:/go/src/github.com/opensentry/aap/model
      - ../config/use/discovery.yml:/discovery.yml
      - ../config/use/aap.yml:/app.yml
    #user: "1000"
    restart: "no"

networks:
  lockdown: # No external network allowed - used for storage services
    name: opensentry_lockdown
    internal: true
