version: '3.7'

services:

  create-clients:
    image: charmixer/hydra-tools:0.0.0
    volumes:
      - ../config/use/clients.yml:/in.yml
      - ../config/use/aapui.yml:/aapui.yml
      - ../config/use/aap.yml:/aap.yml
      - ../config/use/idpui.yml:/idpui.yml
      - ../config/use/idp.yml:/idp.yml
      - ../config/use/meui.yml:/meui.yml
      - ../config/use/oidc.yml:/oidc.yml
    command: hydra-tools
    networks:
      - lockdown
    user: "1000"
    restart: "no"

networks:
  lockdown:
    name: opensentry_lockdown
