version: '3.7'

services:

  idp-migrate:
    build:
      context: ../../idp
      dockerfile: Dockerfile
    entrypoint: ""
    command:
      ./idp --migrate
    networks:
      - lockdown
    environment:
      - CONFIG_DISCOVERY_PATH=/discovery.yml
      - CONFIG_APP_PATH=/app.yml
    volumes:
      - ../../idp/model:/go/src/github.com/opensentry/idp/model
      - ../config/use/discovery.yml:/discovery.yml
      - ../config/use/idp.yml:/app.yml

      - ./certs/neo4j-cert.pem:/etc/ssl/certs/neo4j.pem
    #user: "1000"
    restart: "no"

networks:
  lockdown: # No external network allowed - used for storage services
    name: opensentry_lockdown
    internal: true
