version: '3.7'

services:

  hydra-migrate:
    image: oryd/hydra:v1.0.9
    command:
      migrate sql -e --yes --config /hydra.yml
    networks:
      - lockdown
    volumes:
      - ../config/use/hydra.yml:/hydra.yml
    user: "1000"
    restart: "no"

networks:
  lockdown: # No external network allowed - used for storage services
    name: opensentry_lockdown
    internal: true
