csrf:
  authkey: RumVr1olC62zfFghttlVJqQalQRoC058i3Y6Gx1J1JVchIYhYyUlP+xzjdep4ov5IRGcFg8HAkSGFbvaCDE/ag==
log:
  debug: 1
  format: default
oauth2:
  callback: https://aa.localhost/callback
  client:
    id: 919e2026-06af-4c82-9d84-6af4979d9e7a
    secret: HXKVZsdNEAN8TXu7BAfR4sZJgYVa2GgdDYbR6R4AFnk5y2aU0sQirNIIoAcpOUh/aZnrnRikR4QEXYfzxnzyJw==
  scopes:
    required:
    - openid
    - offline
    - aap:read:scopes
    - aap:read:consents
    - aap:create:consents
    - aap:delete:consents
    - aap:read:consents:authorize
    - aap:create:consents:authorize
    - aap:create:consents:reject
    - aap:read:subscriptions
    - aap:read:publishes
serve:
  public:
    port: 443
  tls:
    cert:
      path: /srv/certs/aapui-cert.pem
    key:
      path: /srv/certs/aapui-key.pem
session:
  authkey: jrZo0gv1BZh1kh5milvfLH/EhEWS0lcrzQZo0tbFL1BU4tCDa/hMcXTLdHY2TMPb2Wiw9xcu2FeUuzWLDDtSXQ==
provider:
  name: Consent Provider
