csrf:
  authkey: ENd8luqAp6Zl9gb2pjt/Pf0lZ8GJeeTWDyZobZvy+ybJAf81TN4WB+4pSznzK3x4Irpk+Eq0PKDG5rkcH9O+iQ==
log:
  debug: 1
  format: default
oauth2:
  callback: https://id.localhost/callback
  client:
    id: c7f1afc4-1e1f-484e-b3c2-0519419690cb
    secret: Z61hRd4e6PSosJk+vfiIOgrYvpw5eLBIg+VqFWqN5WOvpGfUnexqQOmh0AfwM8KCMGG90Oqln45NpkMBBSINCw==
  scopes:
    required:
    - openid
    - offline
    - idp:read:identities
    - idp:create:invites
    - idp:read:invites
    - idp:create:invites:send
    - idp:create:invites:claim
    - idp:read:humans
    - idp:read:humans:logout
    - idp:create:humans:logout
    - idp:update:humans:logout
    - idp:create:humans:recover
    - idp:create:humans
    - idp:create:humans:authenticate
    - idp:update:humans:recoververification
    - idp:update:humans:deleteverification
    - idp:read:challenges
    - idp:create:challenges
    - idp:update:challenges:verify
    - idp:create:humans:emailchange
    - idp:update:humans:emailchange
serve:
  public:
    port: 443
  tls:
    cert:
      path: /srv/certs/idpui-cert.pem
    key:
      path: /srv/certs/idpui-key.pem
session:
  authkey: kENBedOvRJGjaQEtuS0YT8OdFzT/VxZCiVO7aGX8+SsMOhfJAovpkU63ZJxsk0eACXnRgwNW8qVMPeqypLRHXQ==
